server:
  port: 80

spring:
  application:
    name: court
  mvc:
    view:
      suffix: .html
      prefix: /
  profiles:
    active: ${ENV_NAME:local}
  cache:
    redis:
      key-prefix: "${spring.application.name}:${spring.profiles.active}:cache:"
      time-to-live: 600s
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
